### ISSUE TITLE
http url ?

### ISSUE THREAD

**Issue by firaskudsy** [christocracy/cordova-background-geolocation-SampleApp#1]
am using this application and set the url to point to my php page that read the post and insert it into mysql table, but i get 0 in latitude and longtitude !!? when i test the code on my ionic application it get the latitude and longtitude values and post them to the server but with delay like every 1 minute or around 800 m !! the setting am using in both my ionic app and on this application is the same 

     desiredAccuracy: 0,
  stationaryRadius: 30,
     distanceFilter: 50,
         locationUpdateInterval: 1000,
                      fastestLocationUpdateInterval: 1000,
             activityRecognitionInterval:1000,
             stopTimeout:0,

any help ?

**Comment by christocracy** [comment]
Have you paid for the Premium version?

http://christocracy.github.io/cordova-background-geolocation/


On Monday, June 15, 2015, firaskudsy <notifications@github.com> wrote:

> am using this application and set the url to point to my php page that
> read the post and insert it into mysql table, but i get 0 in latitude and
> longtitude !!? when i test the code on my ionic application it get the
> latitude and longtitude values and post them to the server but with delay
> like every 1 minute or around 800 m !! the setting am using in both my
> ionic app and on this application is the same
>
>  desiredAccuracy: 0,
>
> stationaryRadius: 30,
> distanceFilter: 50,
> locationUpdateInterval: 1000,
> fastestLocationUpdateInterval: 1000,
> activityRecognitionInterval:1000,
> stopTimeout:0,
>
> any help ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-background-geolocation-SampleApp/issues/1>
> .
>


-- 
Snet from Gmail Mobile

**Comment by firaskudsy** [comment]
no am using the free version, as i read the free version suppose to post the location, now i did another test, with multiple setting values , like distanceFilter = 10 , and do the test then change it to 50 and do the test , but the problem now is .. it post the location every one minute , i want it to post every 5 second or lest .. what the problem ? any help ?

**Comment by christocracy** [comment]
But this SampleApp is designed for the Premium version.

On Monday, June 15, 2015, firaskudsy <notifications@github.com> wrote:

> no am using the free version, as i read the free version suppose to post
> the location, now i did another test, with multiple setting values , like
> distanceFilter = 10 , and do the test then change it to 50 and do the test
> , but the problem now is .. it post the location every one minute , i want
> it to post every 5 second or lest .. what the problem ? any help ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-background-geolocation-SampleApp/issues/1#issuecomment-111968791>
> .
>


-- 
Snet from Gmail Mobile

**Comment by firaskudsy** [comment]
what about the plugin ?  https://github.com/christocracy/cordova-plugin-background-geolocation
 am using this one in my ionic app, and i compare the functionality with the sample app. so how the plugin work ? the same as described ?

**Comment by christocracy** [comment]
You cannot expect this App to work with the free version (especially on
Android).  The settings you see on the settings screen only exist in the
Premium version.  There are a few that are common to both, but the free
version is incompatible.

You must install the premium version for this app to work:



On Monday, June 15, 2015, Chris Scott <christocracy@gmail.com> wrote:

> But this SampleApp is designed for the Premium version.
>
> On Monday, June 15, 2015, firaskudsy <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> no am using the free version, as i read the free version suppose to post
>> the location, now i did another test, with multiple setting values , like
>> distanceFilter = 10 , and do the test then change it to 50 and do the test
>> , but the problem now is .. it post the location every one minute , i want
>> it to post every 5 second or lest .. what the problem ? any help ?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/christocracy/cordova-background-geolocation-SampleApp/issues/1#issuecomment-111968791>
>> .
>>
>
>
> --
> Snet from Gmail Mobile
>


-- 
Snet from Gmail Mobile

**Comment by firaskudsy** [comment]
dose this one minute a limitation for the free version ?

**Comment by firaskudsy** [comment]
what are the setting for the free version and how oftern it send updates ?

**Comment by firaskudsy** [comment]
i want to use the plugin in my ionic app , i want to use the free vesion.

**Comment by christocracy** [comment]
I cannot answer question about your use of this Premium version SampleApp
with the incompatible Free version.

You should not use this repo unless you've paid for the Premium Version.

If you have questions about the Free version, you should use the free
version's sample app (detailed in its README) and post issues at the free
version repo.

On Monday, June 15, 2015, firaskudsy <notifications@github.com> wrote:

> dose this one minute a limitation for the free version ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-background-geolocation-SampleApp/issues/1#issuecomment-111970494>
> .
>


-- 
Snet from Gmail Mobile

**Comment by firaskudsy** [comment]
ok i will change and post into the free version, many thanks
