### ISSUE TITLE
cordova plugin link

### ISSUE THREAD

**Issue by BrentDietrich** [christocracy/cordova-background-geolocation-SampleApp#2]
Hi Chris,

It looks like the following link doesn't exist:
https://github.com/christocracy/cordova-background-geolocation.git#edge

We're trying to evaluate your premium plugin and we can't seem to get this sampleApp running. 

Thanks in advance

**Comment by christocracy** [comment]
This SampleApp **requires** the Premium version.  

I've posted an Android Sample App on google play.

https://play.google.com/store/apps/details?id=com.transistorsoft.background_geolocation.ionic

**Comment by christocracy** [comment]
The #url doesn't work because that's a private-repo which purchasing the Premium Version grants you access to.

**Comment by BrentDietrich** [comment]
Ahh perfect. Thats what I figured. Just wanted to make sure.
